version: '3.4'

services:
  backend:
    image: ${DOCKER_REGISTRY-}webappwithreact
    build:
      context: .
      dockerfile: WebAppWithReact/Dockerfile
  client:
    image: client
    build:
      context: ./WebAppWithReact/client-app
      dockerfile: Dockerfile
  proxy:
    image: nginx:mainline-alpine
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD_FILE: /run/secrets/sql_password
      ACCEPT_EULA: "Y"
secrets:
  sql_password:
    external: true
